development:
  log_file: log/mailman_dev.log
  mailman:
    maildir: tmp/test_maildir
    ignore_stdin: false
  fio_bank_email: 'keraml@gmail.com'
  api_server_url: 'http://localhost:3000'
  api_server_secret_key: 'secret'
  api_server_secret_token: 'secret'
test:
  log_file: log/mailman_test.log
  mailman:
    maildir: tmp/test_maildir
    ignore_stdin: false
  fio_bank_email: 'keraml@gmail.com'
  api_server_url: 'http://localhost:3000'
  api_server_secret_key: 'secret'
  api_server_secret_token: 'secret'
production:
  log_file: log/mailman_prod.log
  mailman:
    ignore_stdin: true
    maildir: tmp/test_maildir
  fio_bank_email: 'automat@fio.cz'
  api_server_url: 'https://www.progressbar.sk'
  api_server_secret_key: 'secret'
  api_server_secret_token: 'secret'